DECLARE
    V_COUNT INTEGER;
BEGIN
    SELECT COUNT(TABLE_NAME) INTO V_COUNT
    FROM USER_TABLES
    WHERE TABLE_NAME = '__EFMigrationsHistory';

    IF V_COUNT = 0 THEN
        BEGIN
            EXECUTE IMMEDIATE 'CREATE TABLE "__EFMigrationsHistory" (
                "MigrationId" NVARCHAR2(150) NOT NULL,
                "ProductVersion" NVARCHAR2(32) NOT NULL,
                CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
            )';
        END;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE "DadosSensor" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Timestamp" TIMESTAMP(7) NOT NULL,
        "ValorLuminosidade" BINARY_DOUBLE NOT NULL,
        "NomeSensor" NVARCHAR2(2000) NOT NULL,
        CONSTRAINT "PK_DadosSensor" PRIMARY KEY ("Id")
    )';
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE "ProducoesEnergia" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Timestamp" TIMESTAMP(7) NOT NULL,
        "PotenciaGerada" BINARY_DOUBLE NOT NULL,
        "TemperaturaAmbiente" BINARY_DOUBLE NOT NULL,
        "Voltagem" BINARY_DOUBLE NOT NULL,
        "Corrente" BINARY_DOUBLE NOT NULL,
        "LocalPainel" NVARCHAR2(2000) NOT NULL,
        CONSTRAINT "PK_ProducoesEnergia" PRIMARY KEY ("Id")
    )';
END;
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20241121011546_InitialMigration', N'8.0.11');
/

ALTER TABLE "ProducoesEnergia" DROP COLUMN "Corrente";
ALTER TABLE "ProducoesEnergia" DROP COLUMN "LocalPainel";
ALTER TABLE "ProducoesEnergia" DROP COLUMN "Voltagem";
/

ALTER TABLE "DadosSensor" ADD "ProducaoEnergiaId" NUMBER(10) DEFAULT 0 NOT NULL;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE "Paineis" (
        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
        "Nome" NVARCHAR2(2000) NOT NULL,
        "ProducaoMedia" BINARY_DOUBLE NOT NULL,
        "ProducaoEnergiaId" NUMBER(10),
        CONSTRAINT "PK_Paineis" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Paineis_ProducoesEnergia_ProducaoEnergiaId" FOREIGN KEY ("ProducaoEnergiaId") REFERENCES "ProducoesEnergia" ("Id")
    )';
END;
/

CREATE UNIQUE INDEX "IX_DadosSensor_ProducaoEnergiaId" ON "DadosSensor" ("ProducaoEnergiaId");
CREATE INDEX "IX_Paineis_ProducaoEnergiaId" ON "Paineis" ("ProducaoEnergiaId");

ALTER TABLE "DadosSensor" ADD CONSTRAINT "FK_DadosSensor_ProducoesEnergia_ProducaoEnergiaId"
FOREIGN KEY ("ProducaoEnergiaId") REFERENCES "ProducoesEnergia" ("Id") ON DELETE CASCADE;
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20241122002215_AddRelationship', N'8.0.11');
/
